### ISSUE TITLE
Error importing escape

### ISSUE THREAD

**Issue by jecompton** [xen/transforms#1]
I hit this error when using this module:

  File "<my home>/.pyenv/versions/5pips/lib/python3.9/site-packages/transforms/safe_html.py", line 3, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/home/jecompt/.pyenv/versions/3.9.5/lib/python3.9/cgi.py)

The fix is to change that line 3 to `from html import escape`.

**Comment by xen** [comment]
Thank you, updated in latest release
